---
root: true
parser: babel-eslint
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:prettier/recommended
  - plugin:react/recommended
env:
  es6: true
  browser: true
rules:
  semi: off
  import/no-unresolved: off
  no-unused-vars:
    - "error"
    - { argsIgnorePattern: "^_" }
settings:
  react:
    # for now, `version` field must be specified, it will default to `detect` later.
    version: detect
